version: 2.1

jobs:
  nodebuild:
    docker:
      - image: cimg/node:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:k50RE0XSSQ0MSFco66Wn0SXKHOY7zjwicmdw5kDQ8lQ"
      - checkout
      - run: 
          name: Install
          command: yarn install
      - run: 
          name: Build
          command: yarn build

workflows:
  workflow1:
    jobs:
      - nodebuild