version: 2.1

jobs:
  nodebuild:
    docker:
      - image: cimg/node:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:k50RE0XSSQ0MSFco66Wn0SXKHOY7zjwicmdw5kDQ8lQ"
      - checkout
      - restore_cache:
          keys:
            - dependencies_imooc
      - run: 
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_imooc
      - run: 
          name: Build
          command: yarn build
      - run:
          name: Prepare shell commands
          command: chmod +x scripts/deploy.sh
      - run:
          name: Run Deploy to github pages
          command: ./scripts/deploy.sh
          
      


workflows:
  workflow1:
    jobs:
      - nodebuild